made script more verbose

diff --git a/bin/jacorb-wrapper-common b/bin/jacorb-wrapper-common
--- a/bin/jacorb-wrapper-common
+++ b/bin/jacorb-wrapper-common
@@ -1,285 +1,1 @@
-# $Id$
-
-# common part of a wrapper start script.
-# this script is sourced by other scripts
-# do not invoke directly
-
-if [ -z "$WRAPPER_HOME" -o ! -d "$WRAPPER_HOME" ] ; then
-    # WRAPPER_HOME is not set
-
-    # try to locate wrapper executable
-    if [ -z "$WRAPPER_CMD" -o ! -x "$WRAPPER_CMD" ] ; then
-	WRAPPER_CMD=`which wrapper 2> /dev/null`
-    fi
-
-    if [ -z "$WRAPPER_CMD" ] ; then
-	echo "Error: Unable to locate wrapper executable"
-	exit 1
-    fi
-    
-    # resolve links
-    while [ -h "$WRAPPER_CMD" ] ; do
-	ls=`ls -ld "$WRAPPER_CMD"`
-	link=`expr "$ls" : '.*-> \(.*\)$'`
-	if expr "$link" : '/.*' > /dev/null; then
-	    WRAPPER_CMD="$link"
-	else
-	    WRAPPER_CMD=`dirname "$PRG"`"/$link"
-	fi
-    done
-
-    WRAPPER_HOME=`dirname "$WRAPPER_CMD"`/..
-fi
-
-# make path full qualified
-WRAPPER_HOME=`cd "$WRAPPER_HOME" && pwd`
-
-if [ -z "$WRAPPER_CMD" -o ! -x "$WRAPPER_CMD" ] ; then
-    WRAPPER_CMD=$WRAPPER_HOME"/bin/wrapper"
-fi
-
-WRAPPER_LIB="$WRAPPER_HOME"/lib
-
-if [ ! -d "$WRAPPER_LIB" ] ; then
-    echo "Error: unable to locate wrapper library"
-    exit 1
-fi
-
-WRAPPER_ARGS=wrapper.java.library.path.1="$WRAPPER_LIB"
-WRAPPER_ARGS="$WRAPPER_ARGS wrapper.java.classpath.1=""$WRAPPER_LIB""/wrapper.jar"
-
-# Get the fully qualified path to the script
-case $0 in
-    /*)
-        SCRIPT="$0"
-        ;;
-    *)
-        PWD=`pwd`
-        SCRIPT="$PWD/$0"
-        ;;
-esac
-
-# Change spaces to ":" so the tokens can be parsed.
-SCRIPT=`echo $SCRIPT | sed -e 's; ;:;g'`
-# Get the real path to this script, resolving any symbolic links
-TOKENS=`echo $SCRIPT | sed -e 's;/; ;g'`
-REALPATH=
-for C in $TOKENS; do
-    REALPATH="$REALPATH/$C"
-    while [ -h "$REALPATH" ] ; do
-        LS="`ls -ld "$REALPATH"`"
-        LINK="`expr "$LS" : '.*-> \(.*\)$'`"
-        if expr "$LINK" : '/.*' > /dev/null; then
-            REALPATH="$LINK"
-        else
-            REALPATH="`dirname "$REALPATH"`""/$LINK"
-        fi
-    done
-done
-# Change ":" chars back to spaces.
-REALPATH=`echo $REALPATH | sed -e 's;:; ;g'`
-
-# Change the current directory to the location of the script
-cd "`dirname "$REALPATH"`"
-
-# Process ID
-PIDFILE="$PIDDIR/$APP_NAME.pid"
-pid=""
-
-# Resolve the location of the 'ps' command
-PSEXE="/usr/bin/ps"
-if [ ! -x $PSEXE ]
-then
-    PSEXE="/bin/ps"
-    if [ ! -x $PSEXE ]
-    then
-        echo "Unable to locate 'ps'."
-        echo "Please report this with the location on your system."
-        exit 1
-    fi
-fi
-
-# Build the nice clause
-if [ "X$PRIORITY" = "X" ]
-then
-    CMDNICE=""
-else
-    CMDNICE="nice -$PRIORITY"
-fi
-
-getpid() {
-    if [ -f $PIDFILE ]
-    then
-        if [ -r $PIDFILE ]
-        then
-            pid=`cat $PIDFILE`
-            if [ "X$pid" != "X" ]
-            then
-                # Verify that a process with this pid is still running.
-                pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
-                if [ "X$pid" = "X" ]
-                then
-                    # This is a stale pid file.
-                    rm -f $PIDFILE
-                    echo "Removed stale pid file: $PIDFILE"
-                fi
-            fi
-        else
-            echo "Cannot read $PIDFILE."
-            exit 1
-        fi
-    fi
-}
-
-testpid() {
-    pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
-    if [ "X$pid" = "X" ]
-    then
-        # Process is gone so remove the pid file.
-        rm -f $PIDFILE
-    fi
-}
-
-console() {
-    echo "Running $APP_LONG_NAME..."
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF $WRAPPER_ARGS wrapper.pidfile=$PIDFILE
-    else
-        echo "$APP_LONG_NAME is already running."
-        exit 1
-    fi
-}
- 
-start() {
-    echo "Starting $APP_LONG_NAME..."
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF $WRAPPER_ARGS wrapper.pidfile=$PIDFILE wrapper.daemonize=TRUE
-    else
-        echo "$APP_LONG_NAME is already running."
-        exit 1
-    fi
-}
- 
-stopit() {
-    echo "Stopping $APP_LONG_NAME..."
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        echo "$APP_LONG_NAME was not running."
-    else
-         # Running so try to stop it.
-        kill $pid
-        if [ $? -ne 0 ]
-        then
-            # An explanation for the failure should have been given
-            echo "Unable to stop $APP_LONG_NAME."
-            exit 1
-        fi
-
-        # We can not predict how long it will take for the wrapper to
-        #  actually stop as it depends on settings in wrapper.conf.
-        #  Loop until it does.
-        savepid=$pid
-        CNT=0
-        TOTCNT=0
-        while [ "X$pid" != "X" ]
-        do
-            # Loop for up to 5 minutes
-            if [ "$TOTCNT" -lt "300" ]
-            then
-                if [ "$CNT" -lt "5" ]
-                then
-                    CNT=`expr $CNT + 1`
-                else
-                    echo "Waiting for $APP_LONG_NAME to exit..."
-                    CNT=0
-                fi
-                TOTCNT=`expr $TOTCNT + 1`
-
-                sleep 1
-
-                testpid
-            else
-                pid=
-            fi
-        done
-
-        pid=$savepid
-        testpid
-        if [ "X$pid" != "X" ]
-        then
-            echo "Timed out waiting for $APP_LONG_NAME to exit."
-            echo "  Attempting a forced exit..."
-            kill -9 $pid
-        fi
-
-        pid=$savepid
-        testpid
-        if [ "X$pid" != "X" ]
-        then
-            echo "Failed to stop $APP_LONG_NAME."
-            exit 1
-        else
-            echo "Stopped $APP_LONG_NAME."
-        fi
-    fi
-}
-
-dump() {
-    echo "Dumping $APP_LONG_NAME..."
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        echo "$APP_LONG_NAME was not running."
-
-    else
-        kill -3 $pid
-
-        if [ $? -ne 0 ]
-        then
-            echo "Failed to dump $APP_LONG_NAME."
-            exit 1
-        else
-            echo "Dumped $APP_LONG_NAME."
-        fi
-    fi
-}
-
-case "$1" in
-
-    'console')
-        console
-        ;;
-
-    'start')
-        start
-        ;;
-
-    'stop')
-        stopit
-        ;;
-
-    'restart')
-        stopit
-        start
-        ;;
-
-    'dump')
-        dump
-        ;;
-
-    *)
-        echo "Usage: $0 { console | start | stop | restart | dump }"
-        exit 1
-        ;;
-esac
-
-exit 0
-
-# Local Variables: 
-# mode: sh
-# End:
+# $Id$# common part of a wrapper start script.# this script is sourced by other scripts# do not invoke directlyif [ -z "$WRAPPER_HOME" -o ! -d "$WRAPPER_HOME" ] ; then    # WRAPPER_HOME is not set    # try to locate wrapper executable    if [ -z "$WRAPPER_CMD" -o ! -x "$WRAPPER_CMD" ] ; then	WRAPPER_CMD=`which wrapper 2> /dev/null`    fi    if [ -z "$WRAPPER_CMD" ] ; then	echo "Error: Unable to locate wrapper executable"	exit 1    fi    # resolve links    while [ -h "$WRAPPER_CMD" ] ; do	ls=`ls -ld "$WRAPPER_CMD"`	link=`expr "$ls" : '.*-> \(.*\)$'`	if expr "$link" : '/.*' > /dev/null; then	    WRAPPER_CMD="$link"	else	    WRAPPER_CMD=`dirname "$WRAPPER_CMD"`"/$link"	fi    done    WRAPPER_HOME=`dirname "$WRAPPER_CMD"`/..fi#echo "using WRAPPER_HOME $WRAPPER_HOME"# make path full qualifiedWRAPPER_HOME=`cd "$WRAPPER_HOME" && pwd`if [ -z "$WRAPPER_CMD" -o ! -x "$WRAPPER_CMD" ] ; then    WRAPPER_CMD=$WRAPPER_HOME"/bin/wrapper"fiWRAPPER_LIB="$WRAPPER_HOME"/libif [ ! -d "$WRAPPER_LIB" ] ; then    echo "Error: unable to locate wrapper library: $WRAPPER_LIB"    exit 1fiWRAPPER_ARGS=wrapper.java.library.path.1="$WRAPPER_LIB"WRAPPER_ARGS="$WRAPPER_ARGS wrapper.java.classpath.1=""$WRAPPER_LIB""/wrapper.jar"# Get the fully qualified path to the scriptcase $0 in    /*)        SCRIPT="$0"        ;;    *)        PWD=`pwd`        SCRIPT="$PWD/$0"        ;;esac# Change spaces to ":" so the tokens can be parsed.SCRIPT=`echo $SCRIPT | sed -e 's; ;:;g'`# Get the real path to this script, resolving any symbolic linksTOKENS=`echo $SCRIPT | sed -e 's;/; ;g'`REALPATH=for C in $TOKENS; do    REALPATH="$REALPATH/$C"    while [ -h "$REALPATH" ] ; do        LS="`ls -ld "$REALPATH"`"        LINK="`expr "$LS" : '.*-> \(.*\)$'`"        if expr "$LINK" : '/.*' > /dev/null; then            REALPATH="$LINK"        else            REALPATH="`dirname "$REALPATH"`""/$LINK"        fi    donedone# Change ":" chars back to spaces.REALPATH=`echo $REALPATH | sed -e 's;:; ;g'`# Change the current directory to the location of the scriptcd "`dirname "$REALPATH"`"# Process IDPIDFILE="$PIDDIR/$APP_NAME.pid"pid=""# Resolve the location of the 'ps' commandPSEXE="/usr/bin/ps"if [ ! -x $PSEXE ]then    PSEXE="/bin/ps"    if [ ! -x $PSEXE ]    then        echo "Unable to locate 'ps'."        echo "Please report this with the location on your system."        exit 1    fifi# Build the nice clauseif [ "X$PRIORITY" = "X" ]then    CMDNICE=""else    CMDNICE="nice -$PRIORITY"figetpid() {    if [ -f $PIDFILE ]    then        if [ -r $PIDFILE ]        then            pid=`cat $PIDFILE`            if [ "X$pid" != "X" ]            then                # Verify that a process with this pid is still running.                pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`                if [ "X$pid" = "X" ]                then                    # This is a stale pid file.                    rm -f $PIDFILE                    echo "Removed stale pid file: $PIDFILE"                fi            fi        else            echo "Cannot read $PIDFILE."            exit 1        fi    fi}testpid() {    pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`    if [ "X$pid" = "X" ]    then        # Process is gone so remove the pid file.        rm -f $PIDFILE    fi}console() {    echo "Running $APP_LONG_NAME..."    getpid    if [ "X$pid" = "X" ]    then        exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF $WRAPPER_ARGS wrapper.pidfile=$PIDFILE    else        echo "$APP_LONG_NAME is already running."        exit 1    fi} start() {    echo "Starting $APP_LONG_NAME..."    getpid    if [ "X$pid" = "X" ]    then        exec $CMDNICE $WRAPPER_CMD $WRAPPER_CONF $WRAPPER_ARGS wrapper.pidfile=$PIDFILE wrapper.daemonize=TRUE    else        echo "$APP_LONG_NAME is already running."        exit 1    fi} stopit() {    echo "Stopping $APP_LONG_NAME..."    getpid    if [ "X$pid" = "X" ]    then        echo "$APP_LONG_NAME was not running."    else         # Running so try to stop it.        kill $pid        if [ $? -ne 0 ]        then            # An explanation for the failure should have been given            echo "Unable to stop $APP_LONG_NAME."            exit 1        fi        # We can not predict how long it will take for the wrapper to        #  actually stop as it depends on settings in wrapper.conf.        #  Loop until it does.        savepid=$pid        CNT=0        TOTCNT=0        while [ "X$pid" != "X" ]        do            # Loop for up to 5 minutes            if [ "$TOTCNT" -lt "300" ]            then                if [ "$CNT" -lt "5" ]                then                    CNT=`expr $CNT + 1`                else                    echo "Waiting for $APP_LONG_NAME to exit..."                    CNT=0                fi                TOTCNT=`expr $TOTCNT + 1`                sleep 1                testpid            else                pid=            fi        done        pid=$savepid        testpid        if [ "X$pid" != "X" ]        then            echo "Timed out waiting for $APP_LONG_NAME to exit."            echo "  Attempting a forced exit..."            kill -9 $pid        fi        pid=$savepid        testpid        if [ "X$pid" != "X" ]        then            echo "Failed to stop $APP_LONG_NAME."            exit 1        else            echo "Stopped $APP_LONG_NAME."        fi    fi}dump() {    echo "Dumping $APP_LONG_NAME..."    getpid    if [ "X$pid" = "X" ]    then        echo "$APP_LONG_NAME was not running."    else        kill -3 $pid        if [ $? -ne 0 ]        then            echo "Failed to dump $APP_LONG_NAME."            exit 1        else            echo "Dumped $APP_LONG_NAME."        fi    fi}case "$1" in    'console')        console        ;;    'start')        start        ;;    'stop')        stopit        ;;    'restart')        stopit        start        ;;    'dump')        dump        ;;    *)        echo "Usage: $0 { console | start | stop | restart | dump }"        exit 1        ;;esacexit 0# Local Variables: # mode: sh# End:
